### ISSUE TITLE
Enable compiling on X86_64

### ISSUE THREAD

**Issue by Giova84** [HaikuArchives/TrackerScript#1]
Sorry, I'm not sure of what would be needed to enable the ability to compile this app under Haiku X86_64; however the fact is that if i attempt to compile this app using GCC5 (via ```setarch x86``` on GCC2_hybrid) I got a bunch of errors:
http://sprunge.us/adUN

Obviously everything is fine by compiling this app using GCC2, but I'd like to start to move some apps (I'm using TrackerScript to make Tracker's addons) on X86_64.
@humdingerb can you give some hints? :-)

**Comment by jessicah** [comment]
You might want &argv.front() instead?

**Comment by Giova84** [comment]
Unfortunately I don't know what should be done to fix the issue; I'd just want to be able to compile this app using GCC5 and so on Haiku X86_64.

**Comment by jessicah** [comment]
The output refers to a single line with argv.begin(). It shows file and line number. Should be a simple substitution to try.

**Comment by jessicah** [comment]
Should be fixed now.

**Comment by Giova84** [comment]
Ok, now it build fine. Thanks.

However (I'm running Haiku gcc2h) after build it using GCC5 and setup my script inside the executable (and placed as usual in /add-ons/Tracker folder), wheh I attempt to launch such addon I got: ```Error Missing library loading Add-On TrackerScript``` I guess that's because X86 is the secondary arch on gcc2_hybrid? I am however able to run X86 (compiled with GCC5) pure apps on gcc2_hybrid.
